### ISSUE TITLE
Linker failed

### ISSUE THREAD

**Issue by savage81** [chrisriesgo/Android-AltBeacon-Library#5]
The lib is working fine, but if I want to build a release apk with the linker, I get always this error:

`
Error	3	The "LinkAssemblies" task failed unexpectedly.
Xamarin.Android.XamarinAndroidException: error XA2006: Reference to metadata item 'Android.Bluetooth.LE.AdvertiseCallback' (defined in 'AndroidAltBeaconLibrary, Version=2.1.4.0, Culture=neutral, PublicKeyToken=null') from 'AndroidAltBeaconLibrary, Version=2.1.4.0, Culture=neutral, PublicKeyToken=null' could not be resolved. ---> Mono.Cecil.ResolutionException: Failed to resolve Android.Bluetooth.LE.AdvertiseCallback
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   --- End of inner exception stack trace ---
   at Xamarin.Android.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext()	Herberstein.Droid
`

**Comment by chrisriesgo** [comment]
@savage81 - Thanks for logging this. I'll have to check and see what's going on.

**Comment by chrisriesgo** [comment]
@savage81 - Do you have a simple repro project that I can look at and run? 

Also, have you looked into the Xamarin Docs on Linking behavior? If the linker is over-aggressively linking away members of an assembly, you can tell the linker to skip linking on that assembly: http://developer.xamarin.com/guides/android/advanced_topics/linking/

**Comment by savage81** [comment]
Thanks for your reply.

I could simply reproduce this problem:
- Create a new Xamarin Forms (portable) Project on Visualstudio
- Install AndroidAltBeaconLibrary 2.1.4 via nuget
- Switch to Release 
Build throws the error above

I tried to exclude the lib AndroidAltBeaconLibrary from linking, as you mentioned, still no luck.

![Screenshot](http://www.coderlabs.at/screenshot.png)

**Comment by savage81** [comment]
Damned. It was not a problem of your lib. That was the issue:
https://forums.xamarin.com/discussion/comment/102548/#Comment_102548

**Comment by chrisriesgo** [comment]
Glad to hear you were able to get around the issue. I've seen that thread. Should have known... :)
